source 'https://github.com/CocoaPods/Specs.git'

target 'AppWords', :exclusive => true do
  pod "AppWords", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "AppWords", :path => "../"

  
end
